"""
title: Image Generation
description: Generate images from text prompts using Pollinations.ai (free, no API key required). Supports multiple styles and aspect ratios.
author: custom
version: 1.0.0
requirements: requests
"""

from pydantic import BaseModel, Field
from typing import Optional
import requests
import urllib.parse


STYLES = {
    "none":         "",
    "photorealistic": "photorealistic, highly detailed, 8k resolution, professional photography",
    "anime":        "anime style, vibrant colors, Studio Ghibli inspired",
    "oil painting": "oil painting, classical art style, textured canvas, masterpiece",
    "watercolor":   "watercolor painting, soft edges, artistic, flowing colors",
    "cinematic":    "cinematic, dramatic lighting, movie still, anamorphic lens",
    "sketch":       "pencil sketch, hand drawn, detailed linework, black and white",
    "3d render":    "3D render, octane render, ray tracing, studio lighting",
}

SIZES = {
    "square":    (1024, 1024),
    "landscape": (1344, 768),
    "portrait":  (768, 1344),
    "wide":      (1920, 1080),
}


class Tools:
    class Valves(BaseModel):
        model: str = Field(
            default="flux",
            description="Image model: flux (best quality), flux-realism, flux-anime, flux-3d, turbo (fastest)"
        )
        default_size: str = Field(
            default="square",
            description="Default image size: square, landscape, portrait, wide"
        )
        default_style: str = Field(
            default="none",
            description="Default style: none, photorealistic, anime, oil painting, watercolor, cinematic, sketch, 3d render"
        )

    def __init__(self):
        self.valves = self.Valves()

    def generate_image(
        self,
        prompt: str,
        style: str = "none",
        size: str = "square",
        negative_prompt: str = "",
    ) -> str:
        """
        Generate an image from a text description using Pollinations.ai (free).

        :param prompt: Description of the image to generate. Be detailed for best results.
        :param style: Visual style — none, photorealistic, anime, oil painting, watercolor, cinematic, sketch, 3d render
        :param size: Image dimensions — square (1024x1024), landscape (1344x768), portrait (768x1344), wide (1920x1080)
        :param negative_prompt: What to avoid in the image e.g. "blurry, low quality, text"
        :return: Generated image displayed inline
        """
        try:
            # Apply style suffix
            style_key = style.lower().strip()
            style_suffix = STYLES.get(style_key, "")
            full_prompt = f"{prompt}, {style_suffix}".strip(", ") if style_suffix else prompt

            # Apply negative prompt defaults
            neg = negative_prompt or "blurry, low quality, watermark, text, ugly, distorted"

            # Get dimensions
            size_key = size.lower().strip()
            w, h = SIZES.get(size_key, (1024, 1024))

            # Pick model
            model = self.valves.model

            # Build Pollinations URL
            encoded_prompt = urllib.parse.quote(full_prompt)
            encoded_neg    = urllib.parse.quote(neg)
            seed           = __import__('random').randint(1, 999999)

            url = (
                f"https://image.pollinations.ai/prompt/{encoded_prompt}"
                f"?model={model}&width={w}&height={h}"
                f"&negative_prompt={encoded_neg}&seed={seed}&nologo=true"
            )

            # Verify the URL is reachable
            resp = requests.head(url, timeout=30, allow_redirects=True)
            if resp.status_code not in (200, 301, 302):
                return f"Image generation failed (HTTP {resp.status_code}). Try again."

            return (
                f"![Generated Image]({url})\n\n"
                f"**Prompt:** {prompt}  \n"
                f"**Style:** {style or 'default'}  |  "
                f"**Size:** {w}x{h}  |  "
                f"**Model:** {model}  \n"
                f"*Generated by Pollinations.ai — [open full size]({url})*"
            )

        except requests.Timeout:
            return "Image generation timed out. Pollinations.ai may be busy — try again in a moment."
        except Exception as e:
            return f"Image generation error: {str(e)}"
